nicer wrapper

diff --git a/not-abc/not-abc-wrapper/not-abc_llvm b/not-abc/not-abc-wrapper/not-abc_llvm
--- a/not-abc/not-abc-wrapper/not-abc_llvm
+++ b/not-abc/not-abc-wrapper/not-abc_llvm
@@ -16,7 +16,7 @@ find_clang()
         fi
     done
 
-    echo "myabc: could not find clang" >&2
+    echo "not-abc: could not find clang" >&2
     echo "Please install LLVM or add clang to your PATH." >&2
     exit 1
 }
@@ -30,8 +30,8 @@ usage()
 {
     cat >&2 <<EOF
 Usage:
-    myabc_llvm [-S] [-o output] file.abc
-    myabc_llvm file.abc [-S] [-o output]
+    not-abc_llvm [-S] [-o output] file.abc
+    not-abc_llvm file.abc [-S] [-o output]
 
 Options:
     -S          Generate assembly only
@@ -62,13 +62,13 @@ while (($# > 0)); do
             ;;
 
         -*)
-            echo "myabc_llvm: unknown option '$1'" >&2
+            echo "not-abc_llvm: unknown option '$1'" >&2
             usage
             ;;
 
         *)
             if [[ -n $input ]]; then
-                echo "myabc_llvm: more than one input file specified" >&2
+                echo "not-abc_llvm: more than one input file specified" >&2
                 usage
             fi
             input=$1
@@ -80,7 +80,7 @@ done
 [[ -n $input ]] || usage
 
 [[ -f $input ]] || {
-    echo "myabc_llvm: input file '$input' not found" >&2
+    echo "not-abc_llvm: input file '$input' not found" >&2
     exit 1
 }
 
@@ -88,7 +88,7 @@ case $input in
     *.abc)
         ;;
     *)
-        echo "myabc_llvm: input file must have the extension '.abc'" >&2
+        echo "not-abc_llvm: input file must have the extension '.abc'" >&2
         exit 1
         ;;
 esac
@@ -100,7 +100,7 @@ asm_file="$base_name.ll"
 
 if $assemble_only; then
     if [[ -n $output ]]; then
-        echo "myabc_llvm: options '-S' and '-o' cannot be used together" >&2
+        echo "not-abc_llvm: options '-S' and '-o' cannot be used together" >&2
 	echo "" >&2
 	usage
         exit 1
@@ -110,7 +110,7 @@ if $assemble_only; then
     exit
 fi
 
-tmp_asm=$(mktemp "${TMPDIR:-/tmp}/myabc.XXXXXXXX").ll
+tmp_asm=$(mktemp "${TMPDIR:-/tmp}/not-abc.XXXXXXXX").ll
 trap 'rm -f "$tmp_asm"' EXIT
 
 "$compiler" < "$input" > "$tmp_asm"
diff --git a/not-abc/not-abc-wrapper/not-abc_simple b/not-abc/not-abc-wrapper/not-abc_simple
--- a/not-abc/not-abc-wrapper/not-abc_simple
+++ b/not-abc/not-abc-wrapper/not-abc_simple
@@ -10,8 +10,8 @@ usage()
 {
     cat >&2 <<EOF
 Usage:
-    myabc_simple [-S] [-o output] file.abc
-    myabc_simple file.abc [-S] [-o output]
+    not-abc_simple [-S] [-o output] file.abc
+    not-abc_simple file.abc [-S] [-o output]
 
 Options:
     -S          Generate assembly only
@@ -42,13 +42,13 @@ while (($# > 0)); do
             ;;
 
         -*)
-            echo "myabc_simple: unknown option '$1'" >&2
+            echo "not-abc_simple: unknown option '$1'" >&2
             usage
             ;;
 
         *)
             if [[ -n $input ]]; then
-                echo "myabc_simple: more than one input file specified" >&2
+                echo "not-abc_simple: more than one input file specified" >&2
                 usage
             fi
             input=$1
@@ -60,7 +60,7 @@ done
 [[ -n $input ]] || usage
 
 [[ -f $input ]] || {
-    echo "myabc_simple: input file '$input' not found" >&2
+    echo "not-abc_simple: input file '$input' not found" >&2
     exit 1
 }
 
@@ -68,7 +68,7 @@ case $input in
     *.abc)
         ;;
     *)
-        echo "myabc_simple: input file must have the extension '.abc'" >&2
+        echo "not-abc_simple: input file must have the extension '.abc'" >&2
         exit 1
         ;;
 esac
@@ -80,7 +80,7 @@ asm_file="$base_name.s"
 
 if $assemble_only; then
     if [[ -n $output ]]; then
-        echo "myabc_simple: options '-S' and '-o' cannot be used together" >&2
+        echo "not-abc_simple: options '-S' and '-o' cannot be used together" >&2
 	echo "" >&2
 	usage
         exit 1
@@ -90,8 +90,8 @@ if $assemble_only; then
     exit
 fi
 
-tmp_asm=$(mktemp "${TMPDIR:-/tmp}/myabc.XXXXXXXX")
-tmp_aout=$(mktemp "${TMPDIR:-/tmp}/myabc.XXXXXXXX")
+tmp_asm=$(mktemp "${TMPDIR:-/tmp}/not-abc.XXXXXXXX")
+tmp_aout=$(mktemp "${TMPDIR:-/tmp}/not-abc.XXXXXXXX")
 trap 'rm -f "$tmp_asm" "$tmp_aout"' EXIT
 
 "$compiler" < "$input" > "$tmp_asm"
